### ISSUE TITLE
Missing file data.h & prob_functions.h.

### ISSUE THREAD

**Issue by kendongdong** [zhangyuygss/SVFSal.caffe#1]
why no data.h & prob_functions.h in em.c ?  Did you write it yourself or publish it online?

**Comment by zhangyuygss** [comment]
The implementation of em part was borrowed from previous work: "Whose vote should count more: Optimal integration
of labels from labelers of unknown expertise". 
We request the codes from the author and compile them to the matlab file: `em_mex.mexa64`,
normally it should work fine.
As for the head files, we are sorry that can't find them too.
We'll consider reimplement it in the future.

**Comment by zhangyuygss** [comment]
#2
